# Training
  output_dir: 'runs'
  eval_samples: 10000

# Training Hyperparameters
  training_args:
    logging_steps: 1
    save_steps: 500
    save_total_limit: 50

    learning_rate: !!float 5e-4
    lr_scheduler_type: 'constant_with_warmup'
    warmup_steps: 500
    weight_decay: 0.05

  # speed-up training
    bf16: True
    torch_compile: True
    ddp_find_unused_parameters: False
    dataloader_prefetch_factor: 4

  # evalutaion
    eval_strategy: 'steps'
    eval_steps: 99999999
    eval_on_start: False
    prediction_loss_only: False
    label_names: []